export const FETCH_USERS = 'ADMIN_FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'ADMIN_FETCH_USERS_SUCCESS'
export const DELETE_USER = 'ADMIN_DELETE_USER'
export const DELETE_USER_SUCCESS = 'ADMIN_USER_SUCCESS'

export const SETTING_USER_LIMIT = 'ADMIN_SETTING_USER_LIMIT'
export const SETTING_SUCCESS = 'ADMIN_SETTING_SUCCESS'

export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD'