export const CREATE_NEW_FOLDER = 'CREATE_NEW_FOLDER'
export const CREATE_NEW_FOLDER_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS'
export const CREATE_NEW_FOLDER_FAIL = 'CREATE_NEW_FOLDER_FAIL'

export const SET_DEFAULT_STATUS = 'SET_DEFAULT_STATUS'

export const LIST_FILES = 'LIST_FILES'

export const LIST_FILES_SUCCESS = 'LIST_FILES_SUCCESS'

export const LIST_FILES_FAIL = 'LIST_FILES_FAIL'
