export const CREATE_NEW_FOLDER = 'CREATE_NEW_FOLDER'
export const CREATE_NEW_FOLDER_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS'
export const CREATE_NEW_FOLDER_FAIL = 'CREATE_NEW_FOLDER_FAIL'

export const UPDATE_STORAGE_FILES = 'UPDATE_STORAGE_FILES'

export const SET_DEFAULT_STATUS = 'SET_DEFAULT_STATUS'

export const LIST_FILES = 'LIST_FILES'
export const LIST_FILES_SUCCESS = 'LIST_FILES_SUCCESS'
export const LIST_FILES_FAIL = 'LIST_FILES_FAIL'


export const SWITCH_FOLDER = 'SWITCH_FOLDER'


export const UPDATE_UPLOAD_LIST = 'UPDATE_UPLOAD_LIST'
export const UPLOAD_FILES = 'UPLOAD_FILES'
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS'
export const UPLOAD_FILES_FAIL = 'UPLOAD_FILES_FAIL'
export const REMOVE_SUCCESS_UPLOADED_FILES = 'REMOVE_SUCCESS_UPLOADED_FILES'

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE'
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL'
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS'


export const CHANGE_DELETE_STATUS = 'CHANGE_DELETE_STATUS'
export const UPDATE_PENDING_DELETE_FILE = 'UPDATE_PENDING_DELETE_FILE'
export const DELETE_FILE = 'DELETE_FILE'
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS'
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL'

export const RENAME_FILE = 'RENAME_FILE'
export const RENAME_FILE_SUCCESS = 'RENAME_FILE_SUCCESS'
export const RENAME_FILE_FAIL = 'RENAME_FILE_FAIL'
export const UPDATE_PENDING_RENAME_FILE = 'UPDATE_PENDING_RENAME_FILE'

export const TOGGLE_FILE_DISPLAY_STYLE = 'TOGGLE_FILE_DISPLAY_STYLE'
export const TOGGLE_CONTROL_MODE = 'TOGGLE_CONTROL_MODE'


export const SHOW_VIEW_MODAL = 'SHOW_VIEW_MODAL'