export const CREATE_NEW_FOLDER = 'CREATE_NEW_FOLDER'
export const CREATE_NEW_FOLDER_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS'
export const CREATE_NEW_FOLDER_FAIL = 'CREATE_NEW_FOLDER_FAIL'

export const UPDATE_STORAGE_FILES = 'UPDATE_STORAGE_FILES'

export const SET_DEFAULT_STATUS = 'SET_DEFAULT_STATUS'

export const LIST_FILES = 'LIST_FILES'
export const LIST_FILES_SUCCESS = 'LIST_FILES_SUCCESS'
export const LIST_FILES_FAIL = 'LIST_FILES_FAIL'


export const SWITCH_PARENTID = 'SWITCH_PARENTID'


export const UPDATE_UPLOAD_LIST = 'UPDATE_UPLOAD_LIST'
export const UPLOAD_FILES = 'UPLOAD_FILES'
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS'
export const UPLOAD_FILES_FAIL = 'UPLOAD_FILES_FAIL'

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE'
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL'
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS'