export const GET_SHARE_FILES = 'GET_SHARE_FILES'
export const GET_SHARE_FILES_SUCCESS = 'GET_SHARE_FILES_SUCCESS'
export const GET_SHARE_FILES_FAIL = 'GET_SHARE_FILES_FAIL'


export const DELETE_SHARE_FILE = 'DELETE_SHARE_FILE'
export const DELETE_SHARE_FILE_SUCCESS = 'DELETE_SHARE_FILE_SUCCESS'
export const DELETE_SHARE_FILE_FAIL = 'DELETE_SHARE_FILE_FAIL'